# momonga-mqtt configuration file (draft)
# NOTE: Currently, almost configurations aren't implemented yet. Don't rely these!

[server]
log_file = "stdout"
log_level = "debug"
pid_file = ""

bind_address = "localhost"
port = 1883
max_connections = 100
socket = ""
connection_timeout = 10

enable_tls = false
tls_port = 8883
cafile = ""
certfile = ""
keyfile = ""
httpport = 9000

[engine]
queue_size = 8192
acceptor_count = "cpu"
lock_pool_size = 64